# Enable FEM subject level talk pages for specific projects

location ~* ^/projects/(?:[\w-]*?/)?jeyhansk/redshift-wrangler/talk/subjects/?(?:[0-9]+)/?$ {
    resolver 1.1.1.1;
    proxy_pass $fe_project_uri;
    proxy_set_header Host $fe_project_host;

    include /etc/nginx/proxy-security-headers.conf;
}

location ~* ^/projects/(?:[\w-]*?/)?erinmc/dark-energy-explorers/talk/subjects/?(?:[0-9]+)/?$ {
    resolver 1.1.1.1;
    proxy_pass $fe_project_uri;
    proxy_set_header Host $fe_project_host;

    include /etc/nginx/proxy-security-headers.conf;
}
