apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: batdetective-org-tls
  labels:
    use-azuredns-solver: "true"
spec:
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: batdetective-org-tls
  dnsNames:
    - batdetective.org
    - "*.batdetective.org"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: batdetective.org
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`batdetective.org`) || HostRegexp(`^.+\.batdetective\.org$`)
      kind: Rule
      services:
        - name: http-frontend
          port: 80
  tls:
    secretName: batdetective-org-tls
