apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: frontend-fallback
spec:
  entryPoints:
    - websecure
    - web # Included so it catches standard HTTP port 80 garbage/scanners too
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      priority: 1 # Forces this to be evaluated last
      services:
        - name: http-frontend
          port: 80
  # No cert defined, nonmatched hosts will use Traefik's self-signed cert
