apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: galaxyzooforum-org-tls
  labels:
    use-azuredns-solver: "true"
spec:
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: galaxyzooforum-org-tls
  dnsNames:
    - galaxyzooforum.org
    - "*.galaxyzooforum.org"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: galaxyzooforum.org
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`galaxyzooforum.org`) || HostRegexp(`^.+\.galaxyzooforum\.org$`)
      kind: Rule
      services:
        - name: http-frontend
          port: 80
  tls:
    secretName: galaxyzooforum-org-tls
