apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: galaxyzoo-org-tls
  labels:
    use-azuredns-solver: "true"
spec:
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: galaxyzoo-org-tls
  dnsNames:
    - galaxyzoo.org
    - "*.galaxyzoo.org"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: galaxyzoo.org
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`galaxyzoo.org`) || HostRegexp(`^.+\.galaxyzoo\.org$`)
      kind: Rule
      services:
        - name: http-frontend
          port: 80
  tls:
    secretName: galaxyzoo-org-tls
