apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: operationwardiary-org-tls
  labels:
    use-azuredns-solver: "true"
spec:
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: operationwardiary-org-tls
  dnsNames:
    - operationwardiary.org
    - "*.operationwardiary.org"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: operationwardiary.org
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`operationwardiary.org`) || HostRegexp(`^.+\.operationwardiary\.org$`)
      kind: Rule
      services:
        - name: http-frontend
          port: 80
  tls:
    secretName: operationwardiary-org-tls
