apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: planetaryresponsenetwork-net-tls
  labels:
    use-azuredns-solver: "true"
spec:
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: planetaryresponsenetwork-net-tls
  dnsNames:
    - planetaryresponsenetwork.net
    - "*.planetaryresponsenetwork.net"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: planetaryresponsenetwork.net
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`planetaryresponsenetwork.net`) || HostRegexp(`^.+\.planetaryresponsenetwork\.net$`)
      kind: Rule
      services:
        - name: http-frontend
          port: 80
  tls:
    secretName: planetaryresponsenetwork-net-tls
