apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: snapshotserengeti-org-tls
  labels:
    use-azuredns-solver: "true"
spec:
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: snapshotserengeti-org-tls
  dnsNames:
    - snapshotserengeti.org
    - "*.snapshotserengeti.org"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: snapshotserengeti.org
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`snapshotserengeti.org`) || HostRegexp(`^.+\.snapshotserengeti\.org$`)
      kind: Rule
      services:
        - name: http-frontend
          port: 80
  tls:
    secretName: snapshotserengeti-org-tls
