apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sunspotter-org-tls
  labels:
    use-azuredns-solver: "true"
spec:
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: sunspotter-org-tls
  dnsNames:
    - sunspotter.org
    - "*.sunspotter.org"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sunspotter.org
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`sunspotter.org`) || HostRegexp(`^.+\.sunspotter\.org$`)
      kind: Rule
      services:
        - name: http-frontend
          port: 80
  tls:
    secretName: sunspotter-org-tls
