apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: theandromedaproject-org-tls
  labels:
    use-azuredns-solver: "true"
spec:
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: theandromedaproject-org-tls
  dnsNames:
    - theandromedaproject.org
    - "*.theandromedaproject.org"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: theandromedaproject.org
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`theandromedaproject.org`) || HostRegexp(`^.+\.theandromedaproject\.org$`)
      kind: Rule
      services:
        - name: http-frontend
          port: 80
  tls:
    secretName: theandromedaproject-org-tls
