apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wormwatchlab-org-tls
  labels:
    use-azuredns-solver: "true"
spec:
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: wormwatchlab-org-tls
  dnsNames:
    - wormwatchlab.org
    - "*.wormwatchlab.org"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: wormwatchlab.org
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`wormwatchlab.org`) || HostRegexp(`^.+\.wormwatchlab\.org$`)
      kind: Rule
      services:
        - name: http-frontend
          port: 80
  tls:
    secretName: wormwatchlab-org-tls
